---
title: "{recalc} Bounds of an independent t-test's p-value and Cohen's d from M/SD/N"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    df_print: paged
    self_contained: true
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc_float: yes
params:
  report_title: !r NULL
  m1: !r NULL
  m2: !r NULL
  sd1: !r NULL
  sd2: !r NULL
  n1: !r NULL
  n2: !r NULL
  m_digits: !r NULL
  sd_digits: !r NULL

  p_operator: !r NULL
  p: !r NULL
  p_digits: !r NULL
  p_methods: !r NULL
  alpha: !r NULL

  d: !r NULL
  d_ci_lower: !r NULL
  d_ci_upper: !r NULL
  direction: !r NULL

  input_rounding: !r NULL
  output_rounding: !r NULL
  d_digits: !r NULL
  hedges_correction: !r NULL
  ci_methods: !r NULL
  include_se_sd_confusion: !r NULL
---

# Report name: `r params$report_title`

This report was generated using {recalc} version `r as.character(packageVersion("recalc"))`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo   = FALSE,
  warning = FALSE,
  message = FALSE
)

library(recalc)
library(knitr)
library(kableExtra)
```

## Analysis overview

```{r}
inputs <- data.frame(
  Parameter = c(
    "M1", "M2", "SD1", "SD2", "N1", "N2",
    "m_digits", "sd_digits",
    "p_operator", "Reported p", "p_digits", "p_methods", "alpha",
    "Reported d", "Reported d CI lower", "Reported d CI upper",
    "Direction",
    "Input rounding", "Output rounding", "d_digits",
    "Hedges' correction", "CI method",
    "Include SE/SD confusion"
  ),
  Value = c(
    params$m1, params$m2, params$sd1, params$sd2, params$n1, params$n2,
    params$m_digits, params$sd_digits,
    params$p_operator, params$p, params$p_digits, params$p_methods, params$alpha,
    params$d, params$d_ci_lower, params$d_ci_upper,
    params$direction,
    if (is.null(params$input_rounding)) "NULL" else as.character(params$input_rounding),
    if (is.null(params$output_rounding)) "NULL" else as.character(params$output_rounding),
    params$d_digits,
    if (is.null(params$hedges_correction)) "NULL" else as.character(params$hedges_correction),
    if (is.null(params$ci_methods)) "NULL" else as.character(params$ci_methods),
    as.character(params$include_se_sd_confusion)
  ),
  stringsAsFactors = FALSE
)

kbl(inputs, caption = "Inputs used in this analysis") |>
  kable_styling(full_width = FALSE)
```

## Recalculation and multiverse

```{r}
res <- recalc::independent_t_test_summary(
  m1 = params$m1,
  m2 = params$m2,
  sd1 = params$sd1,
  sd2 = params$sd2,
  n1 = params$n1,
  n2 = params$n2,
  m_digits = params$m_digits,
  sd_digits = params$sd_digits,

  p_operator = params$p_operator,
  p = params$p,
  p_digits = params$p_digits,
  p_methods = if (identical(params$p_methods, "NULL")) NULL else params$p_methods,
  alpha = params$alpha,

  d = params$d,
  d_ci_lower = params$d_ci_lower,
  d_ci_upper = params$d_ci_upper,
  direction = params$direction,

  input_rounding = params$input_rounding,
  output_rounding = params$output_rounding,
  d_digits = params$d_digits,
  hedges_correction = params$hedges_correction,
  ci_methods = if (identical(params$ci_methods, "NULL")) NULL else params$ci_methods,
  include_se_sd_confusion = params$include_se_sd_confusion
)
```

## Reproduced results

```{r}
res$reproduced |>
  kbl(caption = "Reproduced results under the specified analytic choices") |>
  kable_styling(full_width = FALSE)
```

## Multiverse of p-values

```{r}
plot_multiverse_p(res)
```

## Multiverse of Cohen's d

```{r}
plot_multiverse_d(res)
```





