#' @title Multiverse of chi-square / contingency-table p-values
#'
#' @description
#' Explores the multiverse of *p*-values for a contingency-table test of
#' association that are compatible with a reported table of cell counts (or
#' with a 2x2 table reconstructed from reported proportions). The aim is that
#' whichever statistical package produced a reported *p*-value, that value is
#' covered somewhere in the returned multiverse.
#'
#' The multiverse is generated by varying:
#' \itemize{
#'   \item \strong{Test method} (\code{p_methods}). The chosen tests and the
#'         packages whose default output they reproduce:
#'         \itemize{
#'           \item \code{"pearson"} - Pearson chi-square \emph{without}
#'                 continuity correction. Stata \code{tabulate, chi2}; the
#'                 "Pearson Chi-Square" row in SPSS Crosstabs; the "Chi-Square"
#'                 row in SAS \code{PROC FREQ}; R \code{chisq.test(correct = FALSE)}.
#'           \item \code{"yates"} - Pearson chi-square \emph{with} Yates'
#'                 continuity correction (2x2 only). R's \code{chisq.test()}
#'                 \emph{default} (\code{correct = TRUE}); the "Continuity
#'                 Correction" row in SPSS.
#'           \item \code{"likelihood_ratio"} - likelihood-ratio (G\eqn{^2})
#'                 chi-square. The "Likelihood Ratio" row printed by default in
#'                 SPSS and SAS.
#'           \item \code{"n1_chisq"} - the N\eqn{-}1 (Campbell / Richardson)
#'                 chi-square, \eqn{(N-1)/N} times Pearson. For a 2x2 this is the
#'                 SPSS "Linear-by-Linear Association" value and the
#'                 single-stratum SAS \code{PROC FREQ} Mantel-Haenszel
#'                 chi-square.
#'           \item \code{"fisher"} - Fisher's exact test, two-sided, "minlike"
#'                 convention. SPSS/SAS "Fisher's Exact Test"; R
#'                 \code{fisher.test()} default.
#'           \item \code{"fisher_central"} - Fisher's exact test, two-sided,
#'                 "central" (equal-tailed) convention =
#'                 \code{2 * min(one-sided tails)}; differs from \code{"fisher"}
#'                 for asymmetric tables, and equals the "double the one-sided"
#'                 path used by some SPSS / Prism versions.
#'           \item \code{"fisher_midp"} - central two-sided mid-\emph{p}
#'                 adjusted Fisher test (StatXact, OpenEpi, \code{epitools}
#'                 mid-\emph{p}).
#'           \item \code{"fisher_midp_sas"} - the exact mid-\emph{p} as computed
#'                 by SAS \code{PROC FREQ} (two-sided Fisher \emph{p} minus half
#'                 the point probability of the observed table).
#'           \item \code{"wald_z"} - unpooled (Wald) two-sample proportion
#'                 \emph{z}-test. (The \emph{pooled} two-proportion \emph{z} is
#'                 already covered: its square equals \code{"pearson"}.)
#'         }
#'         For tables larger than 2x2, \code{"yates"}, \code{"fisher_central"},
#'         \code{"fisher_midp"}, \code{"fisher_midp_sas"} and \code{"wald_z"} are
#'         undefined and are dropped (with a message) since they apply only to
#'         2x2 tables; \code{"n1_chisq"} (scaled Pearson) is kept.
#'   \item \strong{Input rounding (optional)}: when the 2x2 table is supplied
#'         via reported proportions (\code{prop1}, \code{prop2}) and group
#'         totals (\code{n1}, \code{n2}), each proportion has been rounded to
#'         \code{prop_digits} decimal places, so the underlying event count is
#'         only known to within an integer interval. Every integer cell-count
#'         table consistent with the reported, rounded proportions is
#'         enumerated and run through each test method. See
#'         \code{\link{recalc_rounding}}. When exact \code{counts} are supplied
#'         instead, there is a single table and no input-rounding multiverse.
#' }
#'
#' Chi-square tests of association are inherently two-sided, so there is no
#' \code{alternative}/\code{direction} axis as in the t-test functions.
#'
#' @param counts A contingency table of cell counts: a numeric matrix, or a
#'   numeric vector in row-major order together with \code{n_rows} and
#'   \code{n_cols}. Supply this \emph{or} the proportion arguments, not both.
#' @param n_rows,n_cols Integer. Dimensions, required only when \code{counts}
#'   is supplied as a flat vector.
#' @param prop1,prop2 Numeric in `[0, 1]`. Reported proportion in the first
#'   outcome level for group 1 and group 2 (the 2x2 reconstruction route).
#' @param n1,n2 Integer. Group totals for the 2x2 reconstruction route.
#' @param prop_digits Integer. Number of decimal places \code{prop1}/\code{prop2}
#'   were reported to. Required for the proportion route. (For percentages
#'   reported to whole numbers, pass proportions to 2 dp with
#'   \code{prop_digits = 2}.)
#' @param rounding One of \code{"either"} (default), \code{"half_up"},
#'   \code{"bankers"}, \code{"truncate"}. See \code{\link{recalc_rounding}}.
#'   Only relevant on the proportion route.
#' @param p Numeric. Reported p-value to compare against (optional).
#' @param p_digits Integer. Number of decimal places the reported p uses.
#'   Required if \code{p} is non-NULL; otherwise defaults to 3 for the
#'   rounded-bound output.
#' @param p_operator Character. Relationship between the reported p and the
#'   actual calculated value. One of \code{"equals"}, \code{"less_than"},
#'   \code{"greater_than"}, \code{"less_than_or_equal_to"},
#'   \code{"greater_than_or_equal_to"}. Default \code{"equals"}.
#' @param p_methods Character vector. Subset of \code{c("pearson", "yates",
#'   "likelihood_ratio", "n1_chisq", "fisher", "fisher_central", "fisher_midp",
#'   "fisher_midp_sas", "wald_z")}. NULL (default) uses all applicable methods.
#' @param fisher_simulate Logical. If TRUE, Fisher's exact p-values for tables
#'   larger than 2x2 are obtained by Monte-Carlo simulation
#'   (\code{simulate.p.value = TRUE}). Default FALSE.
#' @param fisher_B Integer. Number of replicates when \code{fisher_simulate} is
#'   TRUE. Default 1e5.
#'
#' @return A list with three elements:
#'   \describe{
#'     \item{\code{reproduced}}{One-row summary. \code{p_inbounds} is the
#'       \strong{default, gap-aware union decision}: whether the reported
#'       \code{p} falls inside the union of the per-method intervals rather than
#'       merely their convex hull. \code{p_inbounds_hull} keeps the convex-hull
#'       decision for legibility (it is always at least as permissive). The
#'       hull bounds \code{min_p}, \code{max_p}, \code{min_p_rounded},
#'       \code{max_p_rounded} are retained, plus \code{n_method_intervals}
#'       (number of disjoint reproducible intervals), \code{covered_width}
#'       (total width of those intervals at reporting resolution),
#'       \code{hull_width}, and \code{covered_fraction = covered_width /
#'       hull_width} (how much of the hull is actually reproducible; small means
#'       mostly gap).}
#'     \item{\code{p_results}}{Long-format data frame with \code{p_unrounded}
#'       for each combination of analytic choices; compatible with
#'       \code{\link{plot_multiverse_p}}.}
#'     \item{\code{method_intervals}}{Per-method \code{[p_min, p_max]} (and the
#'       rounded bounds), one row per test method.}
#'   }
#'
#' @importFrom stats pchisq dhyper phyper fisher.test pnorm
#' @importFrom dplyr summarise mutate case_when between bind_cols select
#' @importFrom tibble tibble
#' @export
recalc_chisq_p <- function(
    counts = NULL,
    n_rows = NULL, n_cols = NULL,
    prop1 = NULL, prop2 = NULL, n1 = NULL, n2 = NULL, prop_digits = NULL,
    rounding = "either",
    p = NULL,
    p_digits = NULL,
    p_operator = c("equals", "less_than", "greater_than",
                   "less_than_or_equal_to", "greater_than_or_equal_to"),
    p_methods = NULL,
    fisher_simulate = FALSE,
    fisher_B = 1e5
) {
  p_operator <- match.arg(p_operator)
  rounding   <- match.arg(rounding, .recalc_rounding_choices)

  all_methods <- c("pearson", "yates", "likelihood_ratio", "n1_chisq",
                   "fisher", "fisher_central", "fisher_midp", "fisher_midp_sas",
                   "wald_z")
  p_methods <- .validate_methods(p_methods, all_methods, "p_methods")

  # Build the candidate tables (one if exact counts; many if reconstructed
  # from rounded proportions).
  grid <- .build_chisq_grid(
    counts = counts, n_rows = n_rows, n_cols = n_cols,
    prop1 = prop1, prop2 = prop2, n1 = n1, n2 = n2,
    prop_digits = prop_digits, rounding = rounding
  )

  # Drop 2x2-only methods when the table is larger than 2x2.
  if (!grid$is_2x2) {
    twobytwo_only <- c("yates", "fisher_central", "fisher_midp",
                       "fisher_midp_sas", "wald_z")
    keep <- setdiff(p_methods, twobytwo_only)
    dropped <- intersect(p_methods, twobytwo_only)
    if (length(dropped) > 0) {
      message("Dropping 2x2-only method(s) for a larger table: ",
              paste(dropped, collapse = ", "))
    }
    if (length(keep) == 0) {
      stop("No applicable test methods remain for a table larger than 2x2.")
    }
    p_methods <- keep
  }

  if (!is.null(p)) {
    if (is.null(p_digits)) stop("You supplied 'p' but not 'p_digits'.")
    .validate_digits(p_digits, "p_digits", min_val = 1L)
  }
  p_digits <- if (is.null(p_digits)) 3L else as.integer(p_digits)
  p_num    <- if (!is.null(p)) as.numeric(p) else NA_real_

  p_results <- .multiverse_chisq_p_results(
    grid, p_methods, fisher_simulate, fisher_B
  )

  reproduced_out <- .reproduced_p_summary(
    p_results, p_num, p_operator, p_digits = p_digits, rounding = rounding
  )

  # Sharper, gap-aware bounds (the default): each test method spans an interval
  # across the input-rounding reconstruction; between methods there can be gaps
  # that the global [min_p, max_p] hull fills in. The union of per-method
  # intervals is a subset of that hull but still contains every
  # legitimately-producible p. `p_inbounds` is the union decision;
  # `p_inbounds_hull` keeps the convex-hull decision for legibility.
  method_intervals <- .method_intervals(p_results, "p_unrounded", "method",
                                        p_digits, rounding)
  applied <- .apply_union_default(reproduced_out, method_intervals, p_num,
                                  p_operator, p_digits,
                                  inbounds_col = "p_inbounds", value_prefix = "p")

  list(
    reproduced       = applied$reproduced,
    p_results        = p_results,
    method_intervals = applied$method_intervals
  )
}


#' @title Multiverse of contingency-table p-values (alias)
#'
#' @description
#' Convenience wrapper around \code{\link{recalc_chisq_p}} that returns the
#' same result list. Provided for naming symmetry with the other
#' \code{recalc_*} families.
#'
#' @param ... Arguments passed to \code{\link{recalc_chisq_p}}.
#'
#' @return A list with elements \code{reproduced}, \code{p_results}, and
#'   \code{method_intervals}; see \code{\link{recalc_chisq_p}}.
#' @export
recalc_chisq <- function(...) {
  recalc_chisq_p(...)
}


# === Internal: table construction / input-rounding grid =======================

#' Build candidate contingency tables, honouring input rounding.
#'
#' Returns a list with `tables` (a list of integer count matrices), `labels`
#' (a character label per table describing the input adjustment), and
#' `is_2x2`.
#' @keywords internal
.build_chisq_grid <- function(counts, n_rows, n_cols,
                              prop1, prop2, n1, n2, prop_digits, rounding) {
  have_counts <- !is.null(counts)
  have_props  <- !is.null(prop1) || !is.null(prop2)

  if (have_counts && have_props) {
    stop("Supply either 'counts' or the proportion arguments, not both.")
  }
  if (!have_counts && !have_props) {
    stop("Supply a contingency table via 'counts', or a 2x2 table via ",
         "'prop1'/'prop2'/'n1'/'n2'/'prop_digits'.")
  }

  if (have_counts) {
    tab <- .as_count_matrix(counts, n_rows, n_cols)
    return(list(
      tables = list(tab),
      labels = "counts:reported",
      is_2x2 = nrow(tab) == 2L && ncol(tab) == 2L
    ))
  }

  # Proportion-reconstruction route (2x2 only).
  vals <- list(prop1 = prop1, prop2 = prop2, n1 = n1, n2 = n2)
  missing <- names(vals)[vapply(vals, function(z) {
    is.null(z) || length(z) == 0 || is.na(z[1])
  }, logical(1))]
  if (length(missing) > 0) {
    stop("The proportion route needs all of prop1, prop2, n1, n2. Missing: ",
         paste(missing, collapse = ", "), ".")
  }
  if (is.null(prop_digits)) {
    stop("You must supply 'prop_digits' (decimal places of prop1/prop2).")
  }
  .validate_digits(prop_digits, "prop_digits", min_val = 0L)
  prop_digits <- as.integer(prop_digits)

  for (nm in c("prop1", "prop2")) {
    v <- get(nm)
    if (v < 0 || v > 1) stop("'", nm, "' must be a proportion in [0, 1].")
  }
  for (nm in c("n1", "n2")) {
    v <- get(nm)
    if (v <= 0 || v %% 1 != 0) {
      stop("'", nm, "' must be a positive integer group total.")
    }
  }

  e1 <- .feasible_events(prop1, n1, prop_digits, rounding)
  e2 <- .feasible_events(prop2, n2, prop_digits, rounding)
  if (length(e1) == 0 || length(e2) == 0) {
    stop("No integer event counts are consistent with the reported ",
         "proportions and totals.")
  }

  combos <- expand.grid(e1 = e1, e2 = e2,
                        KEEP.OUT.ATTRS = FALSE)
  tables <- vector("list", nrow(combos))
  labels <- character(nrow(combos))
  for (i in seq_len(nrow(combos))) {
    a <- combos$e1[i]; cc <- combos$e2[i]
    # rows = groups, columns = (level 1, level 2)
    tables[[i]] <- matrix(c(a, n1 - a, cc, n2 - cc),
                          nrow = 2L, byrow = TRUE)
    labels[i] <- paste0("events_g1:", a, "|events_g2:", cc)
  }

  list(tables = tables, labels = labels, is_2x2 = TRUE)
}

#' Coerce a count input to an integer-valued matrix.
#' @keywords internal
.as_count_matrix <- function(counts, n_rows, n_cols) {
  if (is.matrix(counts) || is.table(counts)) {
    tab <- matrix(as.numeric(counts), nrow = nrow(counts), ncol = ncol(counts))
  } else if (is.numeric(counts)) {
    if (is.null(n_rows) || is.null(n_cols)) {
      stop("When 'counts' is a vector you must supply 'n_rows' and 'n_cols'.")
    }
    if (length(counts) != n_rows * n_cols) {
      stop("length(counts) (", length(counts), ") != n_rows * n_cols (",
           n_rows * n_cols, ").")
    }
    tab <- matrix(as.numeric(counts), nrow = n_rows, ncol = n_cols, byrow = TRUE)
  } else {
    stop("'counts' must be a matrix, a table, or a numeric vector.")
  }
  if (any(!is.finite(tab)) || any(tab < 0)) {
    stop("All cell counts must be finite and non-negative.")
  }
  if (any(abs(tab - round(tab)) > 1e-8)) {
    stop("All cell counts must be (whole) integers.")
  }
  if (nrow(tab) < 2L || ncol(tab) < 2L) {
    stop("A contingency table needs at least 2 rows and 2 columns.")
  }
  round(tab)
}

#' Integer event counts whose proportion rounds to the reported value.
#'
#' Uses the same rounding-preimage interval machinery as the rest of the
#' package (see [interval_from_digits]) on the proportion, then keeps the
#' integer counts that fall inside.
#' @keywords internal
.feasible_events <- function(prop, n, prop_digits, rounding) {
  int_p <- interval_from_digits(prop, prop_digits, lo = 0, hi = 1,
                                rounding = rounding)
  lo <- ceiling(int_p[1] * n - 1e-9)
  hi <- floor(int_p[2] * n + 1e-9)
  lo <- max(0L, as.integer(lo))
  hi <- min(as.integer(n), as.integer(hi))
  if (hi < lo) return(integer(0))
  seq.int(lo, hi)
}


# === Internal: chi-square / exact-test math ===================================

#' @keywords internal
.expected_counts <- function(tab) {
  outer(rowSums(tab), colSums(tab)) / sum(tab)
}

#' @keywords internal
.chisq_pearson <- function(tab) {
  N <- sum(tab)
  if (N <= 0 || any(rowSums(tab) == 0) || any(colSums(tab) == 0)) {
    return(list(statistic = NA_real_, df = NA_real_, p = NA_real_))
  }
  E <- .expected_counts(tab)
  stat <- sum((tab - E)^2 / E)
  df <- (nrow(tab) - 1L) * (ncol(tab) - 1L)
  list(statistic = stat, df = df, p = pchisq(stat, df, lower.tail = FALSE))
}

#' Yates' continuity-corrected Pearson chi-square (2x2 only).
#'
#' Matches \code{stats::chisq.test(correct = TRUE)}: the correction subtracts
#' \code{min(0.5, |O - E|)} from each absolute deviation, preventing
#' over-correction when the deviation is itself below 0.5.
#' @keywords internal
.chisq_yates <- function(tab) {
  if (nrow(tab) != 2L || ncol(tab) != 2L) {
    return(list(statistic = NA_real_, df = NA_real_, p = NA_real_))
  }
  if (sum(tab) <= 0 || any(rowSums(tab) == 0) || any(colSums(tab) == 0)) {
    return(list(statistic = NA_real_, df = NA_real_, p = NA_real_))
  }
  E <- .expected_counts(tab)
  dev <- abs(tab - E)
  yates <- min(0.5, min(dev))
  stat <- sum((dev - yates)^2 / E)
  list(statistic = stat, df = 1, p = pchisq(stat, 1, lower.tail = FALSE))
}

#' Likelihood-ratio (G^2) chi-square.
#' @keywords internal
.chisq_lr <- function(tab) {
  N <- sum(tab)
  if (N <= 0 || any(rowSums(tab) == 0) || any(colSums(tab) == 0)) {
    return(list(statistic = NA_real_, df = NA_real_, p = NA_real_))
  }
  E <- .expected_counts(tab)
  nz <- tab > 0
  stat <- 2 * sum(tab[nz] * log(tab[nz] / E[nz]))
  df <- (nrow(tab) - 1L) * (ncol(tab) - 1L)
  list(statistic = stat, df = df, p = pchisq(stat, df, lower.tail = FALSE))
}

#' Point (hypergeometric) probability of an observed 2x2 table.
#' @keywords internal
.hyper_point <- function(tab) {
  r1 <- sum(tab[1, ]); r2 <- sum(tab[2, ]); c1 <- sum(tab[, 1])
  dhyper(tab[1, 1], m = r1, n = r2, k = c1)
}

#' Fisher's exact two-sided p-value.
#' @keywords internal
.fisher_p <- function(tab, simulate = FALSE, B = 1e5) {
  out <- tryCatch(
    suppressWarnings(
      fisher.test(tab, alternative = "two.sided",
                  simulate.p.value = simulate, B = B)$p.value
    ),
    error = function(e) NA_real_
  )
  as.numeric(out)
}

#' Central two-sided mid-p adjusted Fisher test (2x2).
#'
#' Halves the point probability off each one-sided exact tail, then doubles
#' the smaller one-sided mid-p (the conventional "central" two-sided mid-p
#' used by StatXact / OpenEpi / epitools).
#' @keywords internal
.fisher_midp <- function(tab) {
  if (nrow(tab) != 2L || ncol(tab) != 2L) return(NA_real_)
  r1 <- sum(tab[1, ]); r2 <- sum(tab[2, ]); c1 <- sum(tab[, 1])
  if (r1 == 0 || r2 == 0 || c1 == 0 || (r1 + r2) - c1 == 0) return(NA_real_)
  a <- tab[1, 1]
  pt_obs <- dhyper(a, m = r1, n = r2, k = c1)
  lower  <- phyper(a,     m = r1, n = r2, k = c1)                       # P(X <= a)
  upper  <- phyper(a - 1, m = r1, n = r2, k = c1, lower.tail = FALSE)   # P(X >= a)
  midp_lower <- lower - 0.5 * pt_obs
  midp_upper <- upper - 0.5 * pt_obs
  min(1, 2 * min(midp_lower, midp_upper))
}

#' SAS PROC FREQ exact mid-p (2x2).
#'
#' Two-sided Fisher exact p minus half the point probability of the observed
#' table, matching SAS \code{PROC FREQ} EXACT mid-p output. Reproduces the
#' value implemented in the \code{reappraised} package as \code{midp.sas}.
#' @keywords internal
.fisher_midp_sas <- function(tab) {
  if (nrow(tab) != 2L || ncol(tab) != 2L) return(NA_real_)
  pf <- .fisher_p(tab, simulate = FALSE)
  if (is.na(pf)) return(NA_real_)
  pt_obs <- .hyper_point(tab)
  max(0, min(1, pf - 0.5 * pt_obs))
}

#' N-1 (Campbell / Richardson) chi-square: (N-1)/N times Pearson.
#'
#' The continuity-uncorrected Pearson statistic scaled by (N-1)/N. For a 2x2
#' table this equals the SPSS "Linear-by-Linear Association" value and the
#' single-stratum SAS \code{PROC FREQ} Mantel-Haenszel chi-square ((N-1) r^2).
#' Increasingly recommended as the asymptotic test, and a clean signature
#' because it is usually reported only by grabbing the wrong output panel row.
#' @keywords internal
.chisq_n1 <- function(tab) {
  pr <- .chisq_pearson(tab)
  if (is.na(pr$statistic)) return(pr)
  N <- sum(tab)
  stat <- (N - 1) / N * pr$statistic
  list(statistic = stat, df = pr$df, p = pchisq(stat, pr$df, lower.tail = FALSE))
}

#' Central (equal-tailed) two-sided Fisher exact p (2x2), non-mid-p.
#'
#' \code{min(1, 2 * min(P(X <= a), P(X >= a)))} under the hypergeometric null.
#' Distinct from the \code{"minlike"} convention that R's \code{fisher.test}
#' (and \code{"fisher"} here) use for asymmetric tables, and equal to the
#' "double the smaller one-sided p" convention used by some SPSS / Prism paths.
#' This is the non-mid-p analogue of \code{fisher_midp}.
#' @keywords internal
.fisher_central <- function(tab) {
  if (nrow(tab) != 2L || ncol(tab) != 2L) return(NA_real_)
  r1 <- sum(tab[1, ]); r2 <- sum(tab[2, ]); c1 <- sum(tab[, 1])
  if (r1 == 0 || r2 == 0 || c1 == 0 || (r1 + r2) - c1 == 0) return(NA_real_)
  a <- tab[1, 1]
  lower <- phyper(a,     m = r1, n = r2, k = c1)                       # P(X <= a)
  upper <- phyper(a - 1, m = r1, n = r2, k = c1, lower.tail = FALSE)   # P(X >= a)
  min(1, 2 * min(lower, upper))
}

#' Unpooled (Wald) two-sample proportion z-test p (2x2).
#'
#' \eqn{z = (\hat p_1 - \hat p_2)/\sqrt{\hat p_1(1-\hat p_1)/n_1 +
#' \hat p_2(1-\hat p_2)/n_2}}, two-sided. Unlike the *pooled* two-proportion z
#' (whose square equals the uncorrected Pearson chi-square, already covered by
#' \code{pearson}), the unpooled / Wald form gives a different p and will not
#' reproduce Pearson. Proportions are of outcome level 1 (column 1) within each
#' group (row).
#' @keywords internal
.wald_z <- function(tab) {
  na_out <- list(statistic = NA_real_, df = NA_real_, p = NA_real_)
  if (nrow(tab) != 2L || ncol(tab) != 2L) return(na_out)
  n1 <- sum(tab[1, ]); n2 <- sum(tab[2, ])
  if (n1 == 0 || n2 == 0) return(na_out)
  p1 <- tab[1, 1] / n1; p2 <- tab[2, 1] / n2
  se <- sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)
  if (!is.finite(se) || se == 0) return(na_out)
  z <- (p1 - p2) / se
  list(statistic = z, df = NA_real_, p = 2 * pnorm(-abs(z)))
}

#' Dispatch a single test method on a single table.
#' @keywords internal
.chisq_one <- function(tab, method, fisher_simulate, fisher_B) {
  switch(
    method,
    pearson          = .chisq_pearson(tab),
    yates            = .chisq_yates(tab),
    likelihood_ratio = .chisq_lr(tab),
    n1_chisq         = .chisq_n1(tab),
    fisher = list(statistic = NA_real_, df = NA_real_,
                  p = .fisher_p(tab, fisher_simulate, fisher_B)),
    fisher_central = list(statistic = NA_real_, df = NA_real_,
                          p = .fisher_central(tab)),
    fisher_midp = list(statistic = NA_real_, df = NA_real_,
                       p = .fisher_midp(tab)),
    fisher_midp_sas = list(statistic = NA_real_, df = NA_real_,
                           p = .fisher_midp_sas(tab)),
    wald_z = .wald_z(tab),
    stop("Unknown method: ", method)
  )
}


# === Internal: p multiverse ===================================================

#' @keywords internal
.multiverse_chisq_p_results <- function(grid, p_methods,
                                        fisher_simulate, fisher_B) {
  rows <- vector("list", 0L)

  for (ti in seq_along(grid$tables)) {
    tab <- grid$tables[[ti]]
    lbl <- grid$labels[ti]
    for (method in p_methods) {
      res <- .chisq_one(tab, method, fisher_simulate, fisher_B)
      if (is.na(res$p)) next
      rows[[length(rows) + 1L]] <- data.frame(
        source           = "counts",
        method           = method,
        input_adj_counts = lbl,
        statistic        = res$statistic,
        df               = res$df,
        p_unrounded      = res$p,
        stringsAsFactors = FALSE
      )
    }
  }

  if (length(rows) == 0L) {
    return(data.frame(
      source = character(), method = character(),
      input_adj_counts = character(),
      statistic = numeric(), df = numeric(), p_unrounded = numeric(),
      stringsAsFactors = FALSE
    ))
  }

  out <- do.call(rbind, rows)
  out[order(out$p_unrounded), ]
}


# (Per-method interval + gap-aware union helpers are shared across the chi-square,
#  t-test p, and Cohen's d functions; see `.method_intervals` / `.union_summary`
#  / `.apply_union_default` in infrastructure.R.)
