#' @title Multiverse of independent-samples t-test p-values from summary statistics
#'
#' @description
#' Explores the multiverse of *p*-values for an independent-samples t-test
#' that are compatible with reported group means, SDs, and sample sizes.
#'
#' The multiverse is generated by varying:
#' \itemize{
#'   \item \strong{Input rounding}: a 3-level grid (lower, reported, upper) is
#'         built around each of \code{m1}, \code{m2}, \code{sd1}, \code{sd2}
#'         within the precision implied by \code{m_digits} / \code{sd_digits}
#'         and \code{rounding}. See \code{\link{recalc_rounding}}.
#'   \item \strong{P-value method}: Student's (pooled) and/or Welch's
#'         (unpooled) *t*-test (\code{p_methods}).
#'   \item \strong{Alternative hypothesis}: \code{"two.sided"} (default),
#'         \code{"less"}, or \code{"greater"} (\code{alternative}). Vectors
#'         are allowed and iterate the multiverse.
#'   \item \strong{Direction}: M1 - M2, M2 - M1, or both (\code{direction}).
#'   \item \strong{SD vs SE confusion (optional)}: if
#'         \code{include_se_sd_confusion = TRUE}, the multiverse also includes
#'         a branch where \code{sd1}/\code{sd2} are reinterpreted as SEs and
#'         converted via \eqn{SD = SE \sqrt{n}}.
#' }
#'
#' The implementation uses the numerically stable tail form
#' \code{pt(-abs(t), df)} for two-sided *p* and the correctly tailed
#' \code{pt(t, df, lower.tail = ...)} for one-sided alternatives, so very
#' small *p*-values do not underflow as they do with \code{1 - pt(abs(t), df)}.
#'
#' @param m1,m2 Numeric. Group means.
#' @param sd1,sd2 Numeric. Group SDs.
#' @param n1,n2 Numeric. Group sample sizes.
#' @param m_digits,sd_digits Integer. Number of decimal places to which the
#'   means / SDs were reported. Required.
#' @param rounding One of \code{"either"} (default), \code{"half_up"},
#'   \code{"bankers"}, \code{"truncate"}. See \code{\link{recalc_rounding}}.
#' @param p Numeric. Reported p-value to compare against (optional).
#' @param p_digits Integer. Number of decimal places the reported p uses.
#'   Required if \code{p} is non-NULL.
#' @param p_operator Character. Relationship between the reported p and the
#'   actual calculated value. One of \code{"equals"}, \code{"less_than"},
#'   \code{"greater_than"}, \code{"less_than_or_equal_to"},
#'   \code{"greater_than_or_equal_to"}. Default \code{"equals"}.
#' @param p_methods Character vector. Subset of \code{c("student_t",
#'   "welch_t")}. NULL (default) uses both.
#' @param alternative Character vector. Subset of \code{c("two.sided",
#'   "less", "greater")}. Default \code{"two.sided"}. Passing a vector
#'   iterates the multiverse over all of them.
#' @param direction Character. One of \code{"m1_minus_m2"} (default),
#'   \code{"m2_minus_m1"}, \code{"both"}.
#' @param mu Numeric. The null value for the mean difference, i.e. the
#'   hypothesised \eqn{\mu_1 - \mu_2}. Default \code{0} (the usual test of no
#'   difference). A non-zero value gives \eqn{t = (\text{difference} - \mu)/SE}
#'   for non-inferiority / equivalence / TOST-style reports where the disclosed
#'   null is a margin rather than zero. A single finite number.
#' @param include_se_sd_confusion Logical. Default FALSE.
#'
#' @return A list with elements \code{reproduced}, \code{p_results}, and
#'   \code{method_intervals}. In \code{reproduced}, \code{p_inbounds} is the
#'   \strong{default, gap-aware union decision} (whether the reported *p* falls
#'   inside the union of the per-method intervals rather than merely their
#'   convex hull); \code{p_inbounds_hull} keeps the convex-hull decision for
#'   legibility (always at least as permissive). The hull bounds (\code{min_p},
#'   \code{max_p}, and rounded versions) are retained, plus
#'   \code{n_method_intervals}, \code{covered_width}, \code{hull_width}, and
#'   \code{covered_fraction = covered_width / hull_width} (how much of the hull
#'   is actually reproducible; small means mostly gap). \code{method_intervals}
#'   gives the per-method \code{[p_min, p_max]}. Here a "method" is a
#'   combination of test variant, alternative, direction, and SD interpretation.
#'
#' @importFrom stats pt qt qnorm uniroot
#' @importFrom dplyr summarise mutate case_when between bind_cols select rename
#' @importFrom tibble tibble
#' @export
recalc_independent_t_p <- function(
    m1, m2, sd1, sd2, n1, n2,
    m_digits = NULL,
    sd_digits = NULL,
    rounding = "either",
    p = NULL,
    p_digits = NULL,
    p_operator = c("equals", "less_than", "greater_than",
                   "less_than_or_equal_to", "greater_than_or_equal_to"),
    p_methods = NULL,
    alternative = "two.sided",
    direction = c("m1_minus_m2", "m2_minus_m1", "both"),
    mu = 0,
    include_se_sd_confusion = FALSE
) {
  direction  <- match.arg(direction)
  p_operator <- match.arg(p_operator)

  .validate_msd_inputs(m1, m2, sd1, sd2, n1, n2, m_digits, sd_digits)
  m_digits  <- as.integer(m_digits)
  sd_digits <- as.integer(sd_digits)
  rounding  <- match.arg(rounding, .recalc_rounding_choices)

  if (length(mu) != 1L || !is.finite(mu)) {
    stop("'mu' must be a single finite numeric value (the null mean difference).")
  }
  mu <- as.numeric(mu)

  alternative <- .validate_alternative(alternative)
  p_methods   <- .validate_methods(p_methods, c("student_t", "welch_t"), "p_methods")

  if (!is.null(p)) {
    if (is.null(p_digits)) {
      stop("You supplied 'p' but not 'p_digits'.")
    }
    .validate_digits(p_digits, "p_digits", min_val = 1L)
  }
  if (is.null(p_digits)) {
    # No reported p: still need a precision for rounded-bound output.
    p_digits <- 3L
  } else {
    p_digits <- as.integer(p_digits)
  }
  p_num <- if (!is.null(p)) as.numeric(p) else NA_real_

  p_results <- .multiverse_p_results(
    m1, m2, sd1, sd2, n1, n2,
    m_digits, sd_digits, rounding,
    p_methods, alternative, direction,
    include_se_sd_confusion, mu
  )

  reproduced_out <- .reproduced_p_summary(p_results, p_num, p_operator,
                                          p_digits = p_digits, rounding = rounding)

  # Sharper, gap-aware bounds (the default). A "method" here is a combination of
  # the discrete analytic choices (test variant, alternative, direction, SD
  # interpretation); within each, the input-rounding grid gives an interval.
  # `p_inbounds` is the union decision; `p_inbounds_hull` keeps the convex hull.
  method_intervals <- .method_intervals(
    p_results, "p_unrounded",
    c("p_method", "alternative", "direction", "sd_interpretation"),
    p_digits, rounding
  )
  applied <- .apply_union_default(reproduced_out, method_intervals, p_num,
                                  p_operator, p_digits,
                                  inbounds_col = "p_inbounds", value_prefix = "p")

  list(
    reproduced       = applied$reproduced,
    p_results        = p_results,
    method_intervals = applied$method_intervals
  )
}


#' @title Multiverse of Cohen's d / Hedges' g and CIs from summary statistics
#'
#' @description
#' Explores the multiverse of standardised-mean-difference effect sizes and
#' confidence intervals that are compatible with reported group means, SDs,
#' and sample sizes for an independent-samples comparison.
#'
#' The multiverse is generated by varying:
#' \itemize{
#'   \item \strong{Input rounding}: same 3-level grid over m1/m2/sd1/sd2 as
#'         in \code{\link{recalc_independent_t_p}}.
#'   \item \strong{Denominator (d_formulas)}:
#'         \itemize{
#'           \item \code{"pooled_df"}: \eqn{s_p =
#'                 \sqrt{((n_1-1)s_1^2 + (n_2-1)s_2^2) / (n_1+n_2-2)}}
#'                 (the standard "pooled with df" form, used by SPSS, base R,
#'                 \code{effectsize}, \code{psych}, etc.).
#'           \item \code{"pooled_n"}: \eqn{s_p =
#'                 \sqrt{(n_1 s_1^2 + n_2 s_2^2) / (n_1+n_2)}} (sometimes
#'                 reported, particularly in older psychology textbooks).
#'           \item \code{"simple_avg"}: \eqn{s_p =
#'                 \sqrt{(s_1^2 + s_2^2)/2}} (Cohen's original 1988 form when
#'                 group sizes are equal; some calculators apply it generally).
#'         }
#'   \item \strong{Hedges' correction}:
#'         \itemize{
#'           \item \code{"none"}: plain Cohen's d.
#'           \item \code{"approx"}: \eqn{J = 1 - 3/(4 \cdot df - 1)}
#'                 (the standard small-sample approximation; default in many
#'                 textbooks).
#'           \item \code{"exact"}:
#'                 \eqn{J = \Gamma(df/2) / (\sqrt{df/2}\,\Gamma((df-1)/2))}
#'                 (the gamma-based exact correction, default in
#'                 \code{effectsize::hedges_g} and \code{MBESS}).
#'         }
#'   \item \strong{CI method (ci_methods)}:
#'         \itemize{
#'           \item \code{"wald_t"}: \eqn{d \pm t_{1-\alpha/2,\,df_s}\,SE(d)}
#'                 with pooled df.
#'           \item \code{"wald_z"}: \eqn{d \pm z_{1-\alpha/2}\,SE(d)}
#'                 (normal-approx Wald, common in meta-analytic conventions).
#'           \item \code{"welch_t"}: like \code{"wald_t"} but with Welch df.
#'           \item \code{"nct"}: noncentral-t inversion (Cumming style, used
#'                 by \code{MBESS} and \code{effectsize} for exact CIs).
#'         }
#'   \item \strong{SE-of-d formula (se_formulas)}: used only for the Wald
#'         methods, since NCT does not depend on a closed-form SE.
#'         \itemize{
#'           \item \code{"hedges_olkin"}: \eqn{\sqrt{(n_1+n_2)/(n_1 n_2)
#'                 + d^2/(2(n_1+n_2))}} (Hedges & Olkin 1985, eq. 8.2;
#'                 \eqn{N} in the second term).
#'           \item \code{"cumming"}: \eqn{\sqrt{(n_1+n_2)/(n_1 n_2)
#'                 + d^2/(2(n_1+n_2-2))}} (Cumming 2012 / Borenstein et al.
#'                 2009; \eqn{df} in the second term).
#'           \item \code{"uncorrected"}: \eqn{\sqrt{(n_1+n_2)/(n_1 n_2)}}
#'                 (drops the \eqn{d^2}-bias correction; common in
#'                 textbook-style calculators and a small-effect-size
#'                 approximation).
#'         }
#'   \item \strong{Direction}: \code{"m1_minus_m2"} (default),
#'         \code{"m2_minus_m1"}, or both.
#'   \item \strong{SD vs SE confusion (optional)}: as for the p-value version.
#' }
#'
#' Hedges' correction is applied to both the point estimate and the CI bounds
#' (i.e. \eqn{g_L = J\,d_L}).
#'
#' @param m1,m2,sd1,sd2,n1,n2,m_digits,sd_digits,rounding,direction,include_se_sd_confusion
#'   See \code{\link{recalc_independent_t_p}}.
#' @param d Numeric. Reported standardised effect size (optional).
#' @param d_ci_lower,d_ci_upper Numeric. Reported CI bounds for d (optional).
#' @param d_digits Integer. Number of decimal places d / its CI use.
#'   Required if \code{d} is non-NULL.
#' @param d_formulas Character vector. Subset of \code{c("pooled_df",
#'   "pooled_n", "simple_avg")}. NULL (default) uses all three.
#' @param hedges_correction Character vector. Subset of \code{c("none",
#'   "approx", "exact")}. NULL (default) uses all three. Logical
#'   \code{TRUE}/\code{FALSE} are also accepted for back-compat
#'   (\code{TRUE} -> \code{c("approx", "exact")}, \code{FALSE} ->
#'   \code{"none"}).
#' @param ci_methods Character vector. Subset of \code{c("wald_t", "wald_z",
#'   "welch_t", "nct")}. NULL (default) uses all four.
#' @param se_formulas Character vector. Subset of \code{c("hedges_olkin",
#'   "cumming", "uncorrected")}. NULL (default) uses all three. Only used
#'   by the Wald CI methods.
#' @param alpha Numeric. CI significance level. Default 0.05.
#'
#' @return A list with elements \code{reproduced}, \code{d_results}, and
#'   \code{method_intervals}. In \code{reproduced}, \code{d_inbounds} is the
#'   \strong{default, gap-aware union decision} for the point estimate;
#'   \code{d_inbounds_hull} keeps the convex-hull decision for legibility. The
#'   hull bounds (\code{min_d}, \code{max_d}, and rounded versions) are retained,
#'   plus \code{n_method_intervals}, \code{covered_width}, \code{hull_width},
#'   and \code{covered_fraction}. A "method" here is a combination of the
#'   denominator formula, Hedges correction, direction, and SD interpretation
#'   (the CI-only choices do not move the point estimate).
#'
#' @importFrom stats pt qt qnorm uniroot
#' @importFrom dplyr summarise mutate case_when between bind_cols select rename
#' @importFrom tibble tibble
#' @export
recalc_independent_t_d <- function(
    m1, m2, sd1, sd2, n1, n2,
    m_digits = NULL,
    sd_digits = NULL,
    rounding = "either",
    d = NULL,
    d_ci_lower = NULL,
    d_ci_upper = NULL,
    d_digits = NULL,
    d_formulas = NULL,
    hedges_correction = NULL,
    ci_methods = NULL,
    se_formulas = NULL,
    alpha = 0.05,
    direction = c("m1_minus_m2", "m2_minus_m1", "both"),
    include_se_sd_confusion = FALSE
) {
  direction <- match.arg(direction)

  .validate_msd_inputs(m1, m2, sd1, sd2, n1, n2, m_digits, sd_digits)
  m_digits  <- as.integer(m_digits)
  sd_digits <- as.integer(sd_digits)
  rounding  <- match.arg(rounding, .recalc_rounding_choices)

  if (!is.null(d) && is.null(d_digits)) {
    stop("You supplied 'd' but not 'd_digits'.")
  }
  if (!is.null(d_digits)) {
    .validate_digits(d_digits, "d_digits", min_val = 0L)
    d_digits <- as.integer(d_digits)
  } else {
    # No reported d: still need a precision for rounded-bound output.
    d_digits <- 2L
  }

  d_formulas <- .validate_methods(
    d_formulas, c("pooled_df", "pooled_n", "simple_avg"), "d_formulas"
  )
  ci_methods <- .validate_methods(
    ci_methods, c("wald_t", "wald_z", "welch_t", "nct"), "ci_methods"
  )
  se_formulas <- .validate_methods(
    se_formulas, c("hedges_olkin", "cumming", "uncorrected"), "se_formulas"
  )
  hedges_correction <- .validate_hedges(hedges_correction)

  d_num          <- if (!is.null(d))          as.numeric(d)          else NA_real_
  d_ci_lower_num <- if (!is.null(d_ci_lower)) as.numeric(d_ci_lower) else NA_real_
  d_ci_upper_num <- if (!is.null(d_ci_upper)) as.numeric(d_ci_upper) else NA_real_

  d_results <- .multiverse_d_results(
    m1, m2, sd1, sd2, n1, n2,
    m_digits, sd_digits, rounding,
    d_formulas, hedges_correction, ci_methods, se_formulas,
    alpha, direction, include_se_sd_confusion
  )

  reproduced_out <- .reproduced_d_summary(
    d_results, d_num, d_ci_lower_num, d_ci_upper_num,
    d_digits = d_digits, rounding = rounding
  )

  # Sharper, gap-aware bounds for the point estimate (the default). A "method"
  # is a combination of the discrete choices that change d itself (denominator
  # formula, Hedges correction, direction, SD interpretation); the CI-only
  # choices do not move the point estimate. `d_inbounds` is the union decision;
  # `d_inbounds_hull` keeps the convex hull.
  method_intervals <- .method_intervals(
    d_results, "d_unrounded",
    c("d_formula", "hedges_correction", "direction", "sd_interpretation"),
    d_digits, rounding
  )
  applied <- .apply_union_default(reproduced_out, method_intervals, d_num,
                                  "equals", d_digits,
                                  inbounds_col = "d_inbounds", value_prefix = "d")

  list(
    reproduced       = applied$reproduced,
    d_results        = d_results,
    method_intervals = applied$method_intervals
  )
}


#' @title Combined multiverse of p and d for an independent-samples t-test
#'
#' @description
#' Convenience wrapper that calls both \code{\link{recalc_independent_t_p}}
#' and \code{\link{recalc_independent_t_d}} and merges their outputs into a
#' single result list.
#'
#' @inheritParams recalc_independent_t_p
#' @inheritParams recalc_independent_t_d
#'
#' @return A list with elements \code{reproduced} (one row, combining the d and
#'   p summaries, where \code{d_inbounds} / \code{p_inbounds} are the default
#'   union decisions and \code{d_inbounds_hull} / \code{p_inbounds_hull} the
#'   convex-hull fallbacks), \code{d_results}, \code{p_results},
#'   \code{d_method_intervals}, and \code{p_method_intervals}.
#'
#' @export
recalc_independent_t <- function(
    m1, m2, sd1, sd2, n1, n2,
    m_digits = NULL,
    sd_digits = NULL,
    rounding = "either",
    p = NULL,
    p_digits = NULL,
    p_operator = "equals",
    p_methods = NULL,
    alternative = "two.sided",
    mu = 0,
    d = NULL,
    d_ci_lower = NULL,
    d_ci_upper = NULL,
    d_digits = NULL,
    d_formulas = NULL,
    hedges_correction = NULL,
    ci_methods = NULL,
    se_formulas = NULL,
    alpha = 0.05,
    direction = c("m1_minus_m2", "m2_minus_m1", "both"),
    include_se_sd_confusion = FALSE
) {
  direction <- match.arg(direction)

  res_p <- recalc_independent_t_p(
    m1 = m1, m2 = m2, sd1 = sd1, sd2 = sd2, n1 = n1, n2 = n2,
    m_digits = m_digits, sd_digits = sd_digits,
    rounding = rounding,
    p = p, p_digits = p_digits, p_operator = p_operator,
    p_methods = p_methods, alternative = alternative,
    mu = mu,
    direction = direction,
    include_se_sd_confusion = include_se_sd_confusion
  )

  res_d <- recalc_independent_t_d(
    m1 = m1, m2 = m2, sd1 = sd1, sd2 = sd2, n1 = n1, n2 = n2,
    m_digits = m_digits, sd_digits = sd_digits,
    rounding = rounding,
    d = d, d_ci_lower = d_ci_lower, d_ci_upper = d_ci_upper,
    d_digits = d_digits,
    d_formulas = d_formulas, hedges_correction = hedges_correction,
    ci_methods = ci_methods, se_formulas = se_formulas,
    alpha = alpha,
    direction = direction,
    include_se_sd_confusion = include_se_sd_confusion
  )

  reproduced_out <- dplyr::bind_cols(
    res_d$reproduced |>
      dplyr::select(d, min_d, max_d, min_d_rounded, max_d_rounded,
                    d_inbounds, d_inbounds_hull),
    res_p$reproduced |>
      dplyr::select(p_operator, p, min_p, max_p,
                    min_p_rounded, max_p_rounded, p_inbounds, p_inbounds_hull)
  )

  # Carry the union-region "covered fraction" with d_/p_ prefixes (both families
  # have identically-named descriptor columns, so prefix to avoid a clash).
  reproduced_out$d_covered_fraction <- res_d$reproduced$covered_fraction
  reproduced_out$p_covered_fraction <- res_p$reproduced$covered_fraction

  list(
    reproduced         = reproduced_out,
    d_results          = res_d$d_results,
    p_results          = res_p$p_results,
    d_method_intervals = res_d$method_intervals,
    p_method_intervals = res_p$method_intervals
  )
}


# === Plotting =================================================================

#' Plot multiverse of Cohen's d / Hedges' g and 95% CIs
#'
#' @param res A list returned by \code{\link{recalc_independent_t_d}} or
#'   \code{\link{recalc_independent_t}}.
#'
#' @return A ggplot object.
#' @export
plot_multiverse_d <- function(res) {
  if (is.null(res$d_results) || nrow(res$d_results) == 0) {
    stop("`res` must include a non-empty `d_results` data frame.")
  }

  res_d <- res$d_results |>
    tibble::as_tibble() |>
    dplyr::arrange(.data$d_unrounded) |>
    tibble::rownames_to_column(var = "rowname") |>
    dplyr::mutate(rowname = as.numeric(.data$rowname)) |>
    dplyr::rename(d_plot = "d_unrounded",
                  ci_lower_plot = "ci_lower_unrounded",
                  ci_upper_plot = "ci_upper_unrounded")

  xmin_shade  <- min(res_d$ci_lower_plot, na.rm = TRUE)
  xmax_shade  <- max(res_d$ci_upper_plot, na.rm = TRUE)
  xmin_shade2 <- min(res_d$d_plot, na.rm = TRUE)
  xmax_shade2 <- max(res_d$d_plot, na.rm = TRUE)

  ggplot2::ggplot(
    res_d,
    ggplot2::aes(y = .data$rowname, x = .data$d_plot,
                 xmin = .data$ci_lower_plot, xmax = .data$ci_upper_plot)
  ) +
    ggplot2::annotate("rect", xmin = xmin_shade,  xmax = xmax_shade,
                      ymin = -Inf, ymax = Inf, alpha = 0.3) +
    ggplot2::annotate("rect", xmin = xmin_shade2, xmax = xmax_shade2,
                      ymin = -Inf, ymax = Inf, alpha = 0.4) +
    ggstance::geom_linerangeh() +
    ggplot2::geom_point() +
    ggplot2::theme_linedraw() +
    ggplot2::scale_x_continuous(
      name = "Recalculated standardised mean difference and its 95% CIs",
      breaks = scales::breaks_pretty(n = 8),
      expand = ggplot2::expansion(mult = c(0.1, 0.1))
    ) +
    ggplot2::scale_y_continuous(labels = NULL, name = "Set of analytic choices") +
    ggplot2::ggtitle("Multiverse of d / Hedges' g and 95% CIs")
}

#' Plot multiverse of p-values
#'
#' @param res A list returned by \code{\link{recalc_independent_t_p}} or
#'   \code{\link{recalc_independent_t}}.
#'
#' @return A ggplot object.
#' @export
plot_multiverse_p <- function(res) {
  if (is.null(res$p_results) || nrow(res$p_results) == 0) {
    stop("`res` must include a non-empty `p_results` data frame.")
  }

  res_p <- res$p_results |>
    tibble::as_tibble() |>
    dplyr::arrange(.data$p_unrounded) |>
    tibble::rownames_to_column(var = "rowname") |>
    dplyr::mutate(rowname = as.numeric(.data$rowname)) |>
    dplyr::rename(p_plot = "p_unrounded")

  xmin_shade <- min(res_p$p_plot, na.rm = TRUE)
  xmax_shade <- max(res_p$p_plot, na.rm = TRUE)

  ggplot2::ggplot(
    res_p,
    ggplot2::aes(y = .data$rowname, x = .data$p_plot)
  ) +
    ggplot2::annotate("rect", xmin = xmin_shade, xmax = xmax_shade,
                      ymin = -Inf, ymax = Inf, alpha = 0.4) +
    ggplot2::geom_point() +
    ggplot2::theme_linedraw() +
    ggplot2::scale_x_continuous(
      name = "Recalculated p-values",
      breaks = scales::breaks_pretty(n = 8),
      expand = ggplot2::expansion(mult = c(0.1, 0.1))
    ) +
    ggplot2::scale_y_continuous(labels = NULL, name = "Set of analytic choices") +
    ggplot2::ggtitle("Multiverse of p-values")
}


# === Internal: validation =====================================================

#' @keywords internal
.get_digits <- function(x) {
  if (is.null(x) || length(x) == 0 || is.na(x)) return(0L)
  sx <- sub("^-", "", as.character(x[1L]))
  if (!grepl("\\.", sx)) return(0L)
  nchar(sub("^[^.]*\\.", "", sx))
}

#' @keywords internal
.validate_digits <- function(value, name, min_val = 0L) {
  if (!is.numeric(value) || length(value) != 1L ||
      !is.finite(value) || value < min_val) {
    stop("'", name, "' must be a single non-negative finite number",
         if (min_val > 0) paste0(" >= ", min_val), ".")
  }
  if (value %% 1 != 0) {
    stop("'", name, "' must be an integer number of decimal places, not ",
         value, ".")
  }
  invisible(as.integer(value))
}

#' @keywords internal
.validate_msd_inputs <- function(m1, m2, sd1, sd2, n1, n2, m_digits, sd_digits) {
  vals <- list(m1 = m1, m2 = m2, sd1 = sd1, sd2 = sd2, n1 = n1, n2 = n2)
  missing <- names(vals)[vapply(vals, function(z) {
    is.null(z) || length(z) == 0 || is.na(z[1])
  }, logical(1))]
  if (length(missing) > 0) {
    stop("The following inputs must be supplied: ",
         paste(missing, collapse = ", "), ".")
  }

  if (is.null(m_digits)) {
    stop("You must supply 'm_digits' (decimal places of m1/m2).")
  }
  if (is.null(sd_digits)) {
    stop("You must supply 'sd_digits' (decimal places of sd1/sd2).")
  }
  .validate_digits(m_digits, "m_digits", min_val = 0L)
  .validate_digits(sd_digits, "sd_digits", min_val = 0L)

  obs_m_digits  <- max(.get_digits(m1),  .get_digits(m2))
  obs_sd_digits <- max(.get_digits(sd1), .get_digits(sd2))

  if (m_digits < obs_m_digits) {
    stop("m_digits = ", m_digits,
         " is smaller than the apparent decimal precision of m1/m2 (",
         obs_m_digits, ").")
  }
  if (m_digits > obs_m_digits) {
    warning("m_digits = ", m_digits,
            " is larger than the apparent precision of m1/m2 (",
            obs_m_digits,
            "). This assumes implied trailing zeros (e.g. stored 3.1 = reported 3.10).")
  }
  if (sd_digits < obs_sd_digits) {
    stop("sd_digits = ", sd_digits,
         " is smaller than the apparent decimal precision of sd1/sd2 (",
         obs_sd_digits, ").")
  }
  if (sd_digits > obs_sd_digits) {
    warning("sd_digits = ", sd_digits,
            " is larger than the apparent precision of sd1/sd2 (",
            obs_sd_digits, "). This assumes implied trailing zeros.")
  }
  invisible(TRUE)
}

#' @keywords internal
.validate_methods <- function(input, allowed, name) {
  if (is.null(input)) return(allowed)
  bad <- setdiff(input, allowed)
  if (length(bad) > 0L) {
    stop(name, " contains invalid values: ",
         paste0(bad, collapse = ", "),
         "\nAllowed: ", paste0(allowed, collapse = ", "))
  }
  input
}

#' @keywords internal
.validate_alternative <- function(alternative) {
  allowed <- c("two.sided", "less", "greater")
  if (is.null(alternative)) return("two.sided")
  bad <- setdiff(alternative, allowed)
  if (length(bad) > 0L) {
    stop("alternative contains invalid values: ", paste(bad, collapse = ", "),
         "\nAllowed: ", paste(allowed, collapse = ", "))
  }
  alternative
}

#' @keywords internal
.validate_hedges <- function(hc) {
  allowed <- c("none", "approx", "exact")
  if (is.null(hc)) return(allowed)
  if (is.logical(hc)) {
    if (any(is.na(hc))) stop("'hedges_correction' must not contain NA.")
    # Back-compat: TRUE -> approx + exact; FALSE -> none. If both supplied:
    # union over the mapping.
    out <- character(0)
    if (any(hc))  out <- c(out, "approx", "exact")
    if (any(!hc)) out <- c(out, "none")
    return(unique(out))
  }
  if (!is.character(hc)) {
    stop("'hedges_correction' must be NULL, a logical, or a character vector ",
         "from c('none','approx','exact').")
  }
  bad <- setdiff(hc, allowed)
  if (length(bad) > 0L) {
    stop("hedges_correction contains invalid values: ",
         paste(bad, collapse = ", "),
         "\nAllowed: ", paste(allowed, collapse = ", "))
  }
  hc
}


# === Internal: grid ===========================================================

#' Build the 3^4 corner grid over (m1, m2, sd1, sd2) implied by the rounding.
#' @keywords internal
.build_msd_grid <- function(m1, m2, sd1, sd2, m_digits, sd_digits, rounding) {
  m1_int  <- interval_from_digits(m1,  m_digits,          rounding = rounding)
  m2_int  <- interval_from_digits(m2,  m_digits,          rounding = rounding)
  sd1_int <- interval_from_digits(sd1, sd_digits, lo = 0, rounding = rounding)
  sd2_int <- interval_from_digits(sd2, sd_digits, lo = 0, rounding = rounding)

  m1_vals  <- c(reported = m1,  lower = m1_int[1],  upper = m1_int[2])
  m2_vals  <- c(reported = m2,  lower = m2_int[1],  upper = m2_int[2])
  sd1_vals <- c(reported = sd1, lower = sd1_int[1], upper = sd1_int[2])
  sd2_vals <- c(reported = sd2, lower = sd2_int[1], upper = sd2_int[2])

  adj_levels <- c("reported", "lower", "upper")
  grid <- expand.grid(
    m1_idx  = 1:3, m2_idx  = 1:3,
    sd1_idx = 1:3, sd2_idx = 1:3,
    KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE
  )

  list(
    grid = grid,
    levels = adj_levels,
    m1_vals = m1_vals, m2_vals = m2_vals,
    sd1_vals = sd1_vals, sd2_vals = sd2_vals
  )
}


# === Internal: t-test math ====================================================

#' @keywords internal
.pooled_sd <- function(sd1, sd2, n1, n2, formula) {
  switch(
    formula,
    pooled_df  = sqrt(((n1 - 1) * sd1^2 + (n2 - 1) * sd2^2) / (n1 + n2 - 2)),
    pooled_n   = sqrt((n1 * sd1^2 + n2 * sd2^2) / (n1 + n2)),
    simple_avg = sqrt((sd1^2 + sd2^2) / 2),
    stop("Unknown d_formula: ", formula)
  )
}

#' @keywords internal
.welch_t <- function(m1, m2, sd1, sd2, n1, n2) {
  diff_mean <- m1 - m2
  var1 <- sd1^2; var2 <- sd2^2
  se_welch <- sqrt(var1 / n1 + var2 / n2)
  num_w <- (var1 / n1 + var2 / n2)^2
  den_w <- (var1^2 / (n1^2 * (n1 - 1))) + (var2^2 / (n2^2 * (n2 - 1)))
  df_w  <- num_w / den_w
  t_val <- diff_mean / se_welch
  list(t = t_val, df = df_w, se = se_welch)
}

#' @keywords internal
.student_t <- function(m1, m2, sd1, sd2, n1, n2) {
  # Always uses pooled_df SD for the t-test (the standard form).
  sp <- .pooled_sd(sd1, sd2, n1, n2, "pooled_df")
  se <- sp * sqrt(1 / n1 + 1 / n2)
  list(t = (m1 - m2) / se, df = n1 + n2 - 2, se = se, sp = sp)
}

#' Numerically stable p-value from a t statistic.
#'
#' Uses the precise tail forms so very small p-values do not underflow.
#' @keywords internal
.p_from_t <- function(t, df, alternative) {
  if (is.na(t) || is.na(df)) return(NA_real_)
  switch(
    alternative,
    two.sided = 2 * pt(-abs(t), df = df),
    less      = pt(t, df = df, lower.tail = TRUE),
    greater   = pt(t, df = df, lower.tail = FALSE),
    stop("Unknown alternative: ", alternative)
  )
}


# === Internal: Hedges, SE-of-d, CIs ==========================================

#' @keywords internal
.hedges_J <- function(df, type) {
  if (!is.finite(df) || df <= 1) return(NA_real_)
  switch(
    type,
    none   = 1,
    approx = 1 - 3 / (4 * df - 1),
    # Use lgamma for numerical stability at large df.
    exact  = exp(lgamma(df / 2) - 0.5 * log(df / 2) - lgamma((df - 1) / 2)),
    stop("Unknown hedges correction type: ", type)
  )
}

#' @keywords internal
.se_of_d <- function(d, n1, n2, formula) {
  N <- n1 + n2
  switch(
    formula,
    hedges_olkin = sqrt(N / (n1 * n2) + d^2 / (2 * N)),
    cumming      = sqrt(N / (n1 * n2) + d^2 / (2 * (N - 2))),
    uncorrected  = sqrt(N / (n1 * n2)),
    stop("Unknown se_formula: ", formula)
  )
}

#' Wald CI for d: d +/- crit * SE(d).
#' @keywords internal
.ci_wald <- function(d, se_d, df, crit_method, alpha) {
  crit <- switch(
    crit_method,
    t = qt(1 - alpha / 2, df = df),
    z = qnorm(1 - alpha / 2),
    stop("Unknown crit_method: ", crit_method)
  )
  c(lower = d - crit * se_d, upper = d + crit * se_d)
}

#' Noncentral-t CI on the standardised mean difference.
#'
#' Inverts the noncentral-t distribution at the observed t. Larger ncp
#' shifts the distribution right, so:
#'   - The UPPER ncp bound (delta_upper) satisfies
#'     P(T_ncp(df) <= t_obs) = alpha/2  (lower.tail = TRUE).
#'   - The LOWER ncp bound (delta_lower) satisfies
#'     P(T_ncp(df) >= t_obs) = alpha/2  (lower.tail = FALSE).
#' Then d_bound = delta_bound * sqrt(1/n1 + 1/n2), and Hedges' J is applied
#' to both bounds.
#' @keywords internal
.ci_nct <- function(t_obs, df, n1, n2, alpha, J = 1, max_ncp = 1000) {
  if (is.na(t_obs) || is.na(df)) return(c(lower = NA_real_, upper = NA_real_))

  suppress_nct_warning <- function(expr) {
    withCallingHandlers(
      expr,
      warning = function(w) {
        if (grepl("full precision may not have been achieved in 'pnt\\{final\\}'",
                  conditionMessage(w))) {
          invokeRestart("muffleWarning")
        }
      }
    )
  }

  f_upper <- function(delta) suppress_nct_warning(
    pt(t_obs, df = df, ncp = delta) - alpha / 2
  )
  f_lower <- function(delta) suppress_nct_warning(
    pt(t_obs, df = df, ncp = delta, lower.tail = FALSE) - alpha / 2
  )

  delta_upper <- tryCatch(
    uniroot(f_upper, lower = -max_ncp, upper = max_ncp)$root,
    error = function(e) NA_real_
  )
  delta_lower <- tryCatch(
    uniroot(f_lower, lower = -max_ncp, upper = max_ncp)$root,
    error = function(e) NA_real_
  )

  if (is.na(delta_lower) || is.na(delta_upper)) {
    return(c(lower = NA_real_, upper = NA_real_))
  }

  fac_d <- sqrt(1 / n1 + 1 / n2)
  c(lower = J * delta_lower * fac_d, upper = J * delta_upper * fac_d)
}


# === Internal: p multiverse ===================================================

#' @keywords internal
.multiverse_p_results <- function(
    m1, m2, sd1, sd2, n1, n2,
    m_digits, sd_digits, rounding,
    p_methods, alternative, direction,
    include_se_sd_confusion, mu = 0
) {
  g <- .build_msd_grid(m1, m2, sd1, sd2, m_digits, sd_digits, rounding)
  dir_modes <- if (direction == "both") c("m1_minus_m2", "m2_minus_m1") else direction
  sd_modes  <- if (isTRUE(include_se_sd_confusion)) c("sd", "se_converted") else "sd"

  rows <- vector("list", 0L)

  for (i in seq_len(nrow(g$grid))) {
    row <- g$grid[i, ]
    m1_code  <- g$levels[row$m1_idx];  m2_code  <- g$levels[row$m2_idx]
    sd1_code <- g$levels[row$sd1_idx]; sd2_code <- g$levels[row$sd2_idx]
    adj_label <- paste0("m1:", m1_code, "|m2:", m2_code,
                        "|sd1:", sd1_code, "|sd2:", sd2_code)

    m1_star  <- unname(g$m1_vals [row$m1_idx])
    m2_star  <- unname(g$m2_vals [row$m2_idx])
    sd1_star <- unname(g$sd1_vals[row$sd1_idx])
    sd2_star <- unname(g$sd2_vals[row$sd2_idx])

    for (sd_mode in sd_modes) {
      sd1_eff <- if (sd_mode == "sd") sd1_star else sd1_star * sqrt(n1)
      sd2_eff <- if (sd_mode == "sd") sd2_star else sd2_star * sqrt(n2)
      if (sd1_eff <= 0 || sd2_eff <= 0) next

      stat_s <- .student_t(m1_star, m2_star, sd1_eff, sd2_eff, n1, n2)
      stat_w <- .welch_t  (m1_star, m2_star, sd1_eff, sd2_eff, n1, n2)

      for (dir_mode in dir_modes) {
        sign_factor <- if (dir_mode == "m1_minus_m2") 1 else -1
        # t = (signed difference - mu) / se. With stat$t = (m1-m2)/se this is
        # stat$t * sign_factor - mu/se (mu = 0 reduces to the usual statistic).
        t_s <- stat_s$t * sign_factor - mu / stat_s$se
        t_w <- stat_w$t * sign_factor - mu / stat_w$se

        for (p_method in p_methods) {
          tt <- if (p_method == "student_t") t_s else t_w
          dd <- if (p_method == "student_t") stat_s$df else stat_w$df
          if (is.na(tt) || is.na(dd)) next

          for (alt in alternative) {
            rows[[length(rows) + 1L]] <- data.frame(
              source            = "summary",
              direction         = dir_mode,
              p_method          = p_method,
              alternative       = alt,
              input_adj_stats   = adj_label,
              sd_interpretation = sd_mode,
              t_used            = tt,
              df_used           = dd,
              p_unrounded       = .p_from_t(tt, dd, alt),
              stringsAsFactors  = FALSE
            )
          }
        }
      }
    }
  }

  if (length(rows) == 0L) {
    return(data.frame(
      source = character(), direction = character(),
      p_method = character(), alternative = character(),
      input_adj_stats = character(), sd_interpretation = character(),
      t_used = numeric(), df_used = numeric(), p_unrounded = numeric(),
      stringsAsFactors = FALSE
    ))
  }

  out <- do.call(rbind, rows)
  out[order(out$p_unrounded), ]
}


# === Internal: d multiverse ==================================================

#' @keywords internal
.multiverse_d_results <- function(
    m1, m2, sd1, sd2, n1, n2,
    m_digits, sd_digits, rounding,
    d_formulas, hedges_correction, ci_methods, se_formulas,
    alpha, direction, include_se_sd_confusion
) {
  g <- .build_msd_grid(m1, m2, sd1, sd2, m_digits, sd_digits, rounding)
  dir_modes <- if (direction == "both") c("m1_minus_m2", "m2_minus_m1") else direction
  sd_modes  <- if (isTRUE(include_se_sd_confusion)) c("sd", "se_converted") else "sd"

  rows <- vector("list", 0L)

  for (i in seq_len(nrow(g$grid))) {
    row <- g$grid[i, ]
    m1_code  <- g$levels[row$m1_idx];  m2_code  <- g$levels[row$m2_idx]
    sd1_code <- g$levels[row$sd1_idx]; sd2_code <- g$levels[row$sd2_idx]
    adj_label <- paste0("m1:", m1_code, "|m2:", m2_code,
                        "|sd1:", sd1_code, "|sd2:", sd2_code)

    m1_star  <- unname(g$m1_vals [row$m1_idx])
    m2_star  <- unname(g$m2_vals [row$m2_idx])
    sd1_star <- unname(g$sd1_vals[row$sd1_idx])
    sd2_star <- unname(g$sd2_vals[row$sd2_idx])

    for (sd_mode in sd_modes) {
      sd1_eff <- if (sd_mode == "sd") sd1_star else sd1_star * sqrt(n1)
      sd2_eff <- if (sd_mode == "sd") sd2_star else sd2_star * sqrt(n2)
      if (sd1_eff <= 0 || sd2_eff <= 0) next

      # Pre-compute Welch stats once per (corner, sd_mode); reused below.
      stat_w <- .welch_t(m1_star, m2_star, sd1_eff, sd2_eff, n1, n2)
      df_pooled <- n1 + n2 - 2

      for (dir_mode in dir_modes) {
        sign_factor <- if (dir_mode == "m1_minus_m2") 1 else -1
        diff_mean   <- (m1_star - m2_star) * sign_factor

        for (d_formula in d_formulas) {
          sp <- .pooled_sd(sd1_eff, sd2_eff, n1, n2, d_formula)
          if (!is.finite(sp) || sp <= 0) next
          d_raw <- diff_mean / sp

          for (hc_type in hedges_correction) {
            # Use pooled df for the Hedges correction (standard choice). For
            # Welch-df CIs we still use pooled-df J on the point estimate so
            # the estimate is consistent across CI methods within a row group
            # (df_used in the row reflects the CI's df).
            J <- .hedges_J(df_pooled, hc_type)
            if (is.na(J)) next
            es <- J * d_raw

            for (ci_method in ci_methods) {
              if (ci_method == "nct") {
                # NCT inverts the t-distribution of the test statistic.
                # Use the Student pooled t for symmetry with the rest of d.
                stat_s_for_nct <- .student_t(m1_star, m2_star, sd1_eff, sd2_eff,
                                             n1, n2)
                t_for_nct <- stat_s_for_nct$t * sign_factor
                ci <- .ci_nct(t_for_nct, df_pooled, n1, n2, alpha, J = J)
                rows[[length(rows) + 1L]] <- data.frame(
                  source             = "summary",
                  direction          = dir_mode,
                  d_formula          = d_formula,
                  hedges_correction  = hc_type,
                  ci_method          = ci_method,
                  se_formula         = NA_character_,
                  input_adj_stats    = adj_label,
                  sd_interpretation  = sd_mode,
                  t_used             = t_for_nct,
                  df_used            = df_pooled,
                  d_unrounded        = es,
                  ci_lower_unrounded = unname(ci["lower"]),
                  ci_upper_unrounded = unname(ci["upper"]),
                  stringsAsFactors   = FALSE
                )
              } else {
                # Wald methods: pick df + critical-distribution combo, and
                # iterate over SE formulae.
                df_use <- switch(
                  ci_method,
                  wald_t  = df_pooled,
                  wald_z  = NA_real_,    # z critical doesn't use df
                  welch_t = stat_w$df
                )
                crit_method <- switch(
                  ci_method,
                  wald_t  = "t",
                  wald_z  = "z",
                  welch_t = "t"
                )
                if (ci_method == "welch_t" && (is.na(stat_w$df) || !is.finite(stat_w$df))) next

                for (se_form in se_formulas) {
                  se_d <- .se_of_d(es, n1, n2, se_form)
                  if (!is.finite(se_d)) next
                  ci <- .ci_wald(es, se_d,
                                 df = if (is.na(df_use)) Inf else df_use,
                                 crit_method = crit_method, alpha = alpha)
                  rows[[length(rows) + 1L]] <- data.frame(
                    source             = "summary",
                    direction          = dir_mode,
                    d_formula          = d_formula,
                    hedges_correction  = hc_type,
                    ci_method          = ci_method,
                    se_formula         = se_form,
                    input_adj_stats    = adj_label,
                    sd_interpretation  = sd_mode,
                    t_used             = NA_real_,
                    df_used            = df_use,
                    d_unrounded        = es,
                    ci_lower_unrounded = unname(ci["lower"]),
                    ci_upper_unrounded = unname(ci["upper"]),
                    stringsAsFactors   = FALSE
                  )
                }
              }
            }
          }
        }
      }
    }
  }

  if (length(rows) == 0L) {
    return(data.frame(
      source = character(), direction = character(),
      d_formula = character(), hedges_correction = character(),
      ci_method = character(), se_formula = character(),
      input_adj_stats = character(), sd_interpretation = character(),
      t_used = numeric(), df_used = numeric(),
      d_unrounded = numeric(),
      ci_lower_unrounded = numeric(), ci_upper_unrounded = numeric(),
      stringsAsFactors = FALSE
    ))
  }

  out <- do.call(rbind, rows)
  out[order(out$d_unrounded), ]
}


# === Internal: reproduced-summary builders ===================================

#' Round a multiverse bound to the reporting precision.
#'
#' The reported value (p or d) has already been rounded by the original
#' analyst to `digits` decimal places under some rounding convention. For
#' the `inbounds` comparison to be apples-to-apples, the multiverse's
#' `[min, max]` must be rounded to the same precision under the same
#' convention; otherwise reported values just outside the unrounded
#' multiverse but within rounding tolerance produce spurious `FALSE`s
#' (most visible when the analytic value is within half a ULP of a
#' representational boundary such as p ~ 0 or p ~ 1).
#'
#' For `"either"`, `"half_up"`, and `"bankers"` the closed preimage
#' interval is the symmetric +/-1/2-ULP, so half-up is used as the canonical
#' rounding for the bound. For `"truncate"` the preimage is asymmetric
#' and we use `round_trunc` (toward zero) to match.
#' @keywords internal
.round_for_report <- function(x, digits, rounding) {
  fn <- switch(
    rounding,
    truncate = function(z) roundwork::round_trunc(z, digits),
    bankers  = function(z) round(z, digits),
    half_up  = function(z) roundwork::round_up(z, digits),
    either   = function(z) roundwork::round_up(z, digits),
    stop("Unknown rounding: ", rounding)
  )
  ifelse(is.na(x) | !is.finite(x), x, fn(x))
}

#' @keywords internal
.reproduced_p_summary <- function(p_results, p_num, p_operator,
                                  p_digits, rounding) {
  if (!is.null(p_results) && nrow(p_results) > 0 && "p_unrounded" %in% names(p_results)) {
    summ <- dplyr::summarise(p_results,
                             min_p = min(.data$p_unrounded, na.rm = TRUE),
                             max_p = max(.data$p_unrounded, na.rm = TRUE))
  } else {
    summ <- tibble::tibble(min_p = NA_real_, max_p = NA_real_)
  }

  summ$min_p_rounded <- .round_for_report(summ$min_p, p_digits, rounding)
  summ$max_p_rounded <- .round_for_report(summ$max_p, p_digits, rounding)

  out <- dplyr::bind_cols(summ, tibble::tibble(p = p_num))
  out |>
    dplyr::mutate(
      p_operator = p_operator,
      p_inbounds = dplyr::case_when(
        is.na(.data$p) ~ NA,
        p_operator == "equals" ~ dplyr::between(.data$p,
                                                .data$min_p_rounded,
                                                .data$max_p_rounded),
        p_operator %in% c("less_than", "less_than_or_equal_to") ~ .data$min_p_rounded <= .data$p,
        p_operator %in% c("greater_than", "greater_than_or_equal_to") ~ .data$max_p_rounded >= .data$p
      )
    ) |>
    dplyr::select("p_operator", "p",
                  "min_p", "max_p",
                  "min_p_rounded", "max_p_rounded",
                  "p_inbounds")
}

#' @keywords internal
.reproduced_d_summary <- function(d_results, d_num, d_ci_lower_num, d_ci_upper_num,
                                  d_digits, rounding) {
  if (!is.null(d_results) && nrow(d_results) > 0 && "d_unrounded" %in% names(d_results)) {
    summ <- dplyr::summarise(d_results,
                             min_d = min(.data$d_unrounded, na.rm = TRUE),
                             max_d = max(.data$d_unrounded, na.rm = TRUE))
  } else {
    summ <- tibble::tibble(min_d = NA_real_, max_d = NA_real_)
  }

  summ$min_d_rounded <- .round_for_report(summ$min_d, d_digits, rounding)
  summ$max_d_rounded <- .round_for_report(summ$max_d, d_digits, rounding)

  out <- dplyr::bind_cols(summ, tibble::tibble(d = d_num))
  out |>
    dplyr::mutate(
      d_inbounds = dplyr::case_when(
        is.na(.data$d) ~ NA,
        TRUE ~ dplyr::between(.data$d, .data$min_d_rounded, .data$max_d_rounded)
      )
    ) |>
    dplyr::select("d",
                  "min_d", "max_d",
                  "min_d_rounded", "max_d_rounded",
                  "d_inbounds")
}
